"""Docker Compose and Kubernetes manifest scaffolding from pipeline configuration."""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.schemas.pipeline import PipelineConfigurationSchema

from app.services.export_generators._compat import ev


def _slug(name: str) -> str:
    s = re.sub(r"[^\w\s-]", "", name.lower())
    s = re.sub(r"[-\s]+", "-", s).strip("-")
    return s or "rag-pipeline"


def generate_docker_compose(config: PipelineConfigurationSchema) -> str:
    """Compose stack: API + Postgres + Redis + Qdrant (local dev pattern)."""
    slug = _slug(config.name)
    vs = config.stages.vector_store
    index = vs.index_name
    provider_note = ev(vs.provider)
    return f"""# RAG pipeline — {config.name}
# Generated by RAG Studio
# Vector store (config): {provider_note}, index/collection: {index}
#
# Build your API image (Dockerfile in ./api), set OPENAI_API_KEY in .env, then:
#   docker compose up -d

name: {slug}

services:
  api:
    image: {slug}-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://vector-db:6333
      - OPENAI_API_KEY=${{OPENAI_API_KEY}}
      - PINECONE_API_KEY=${{PINECONE_API_KEY:-}}
      - DATABASE_URL=${{DATABASE_URL:-postgresql+asyncpg://rag:rag@db:5432/rag}}
      - REDIS_URL=${{REDIS_URL:-redis://redis:6379/0}}
      - VECTOR_INDEX={index}
    depends_on:
      - db
      - redis
      - vector-db
    networks:
      - rag-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: rag
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - rag-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - rag-network
    restart: unless-stopped

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  pg_data:
  qdrant_data:

networks:
  rag-network:
    driver: bridge
"""


def generate_kubernetes(config: PipelineConfigurationSchema) -> str:
    """Multi-document YAML: Namespace, ConfigMap, Qdrant, API Deployment/Service."""
    slug = _slug(config.name)
    ns = slug[:63]
    vs = config.stages.vector_store
    index = vs.index_name
    emb = config.stages.embedding
    gen = config.stages.generation

    return f"""# RAG pipeline — {config.name}
# Generated by RAG Studio
# Apply: kubectl apply -f manifests.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: {ns}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {slug}-config
  namespace: {ns}
data:
  VECTOR_INDEX: "{index}"
  EMBEDDING_MODEL: "{emb.model}"
  LLM_MODEL: "{gen.model}"
  QDRANT_URL: "http://qdrant.{ns}.svc.cluster.local:6333"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: {ns}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: data
              mountPath: /qdrant/storage
      volumes:
        - name: data
          emptyDir: {{}}
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: {ns}
spec:
  selector:
    app: qdrant
  ports:
    - port: 6333
      targetPort: 6333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {slug}-api
  namespace: {ns}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {slug}-api
  template:
    metadata:
      labels:
        app: {slug}-api
    spec:
      containers:
        - name: api
          image: your-registry/{slug}-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {slug}-config
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {slug}-secrets
                  key: openai-api-key
                  optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: {slug}-api
  namespace: {ns}
spec:
  selector:
    app: {slug}-api
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
---
# Create secrets: kubectl create secret generic {slug}-secrets -n {ns} ...
"""
