"""Pydantic schemas package — re-exports every public schema class.

Import pattern inside the app:
    from app.schemas import PipelineConfigurationSchema, SaveConfigRequest
"""

# ── Pipeline (core types shared by all modules) ───────────────────────────────
from app.schemas.pipeline import (
    ChunkingConfigSchema,
    ChunkingStrategy,
    CloudProvider,
    CostBreakdownSchema,
    CostEstimateSchema,
    DataIngestionConfigSchema,
    DataIngestionMetadataSchema,
    DataIngestionPreprocessingSchema,
    EmbeddingConfigSchema,
    EmbeddingProvider,
    EvaluationConfigSchema,
    FilterOperator,
    GenerationConfigSchema,
    GenerationProvider,
    HybridSearchConfig,
    MemoryConfigSchema,
    MemoryType,
    MetadataFilter,
    ModelTier,
    MultiQueryConfigSchema,
    OutputFormat,
    ParentChildConfigSchema,
    PerformanceEstimateSchema,
    PipelineConfigurationSchema,
    PipelineMetadataSchema,
    PipelineStagesSchema,
    RAGBaseModel,
    RerankingConfigSchema,
    RetrievalConfigSchema,
    RetrievalStrategy,
    RoutingConfigSchema,
    RoutingRuleSchema,
    SimilarityMetric,
    VectorStoreCloudConfigSchema,
    VectorStoreConfigSchema,
    VectorStoreConfigurationSchema,
    VectorStoreProvider,
)

# ── Projects (P4-1) ───────────────────────────────────────────────────────────
from app.schemas.project import (
    AutopilotBuildSummary,
    PaginatedProjectsResponse,
    PipelineConfigSummary,
    ProjectCreateRequest,
    ProjectDetailResponse,
    ProjectSummary,
    ProjectUpdateRequest,
)

# ── Designer ──────────────────────────────────────────────────────────────────
from app.schemas.designer import (
    ConfigListItem,
    ConfigListResponse,
    CostRequest,
    CostResponse,
    ExportFormat,
    ExportRequest,
    ExportResponse,
    SaveConfigRequest,
    SaveConfigResponse,
    UpdateDesignerConfigRequest,
)

# ── Autopilot ─────────────────────────────────────────────────────────────────
from app.schemas.autopilot import (
    AgentDecisionSchema,
    BuildArtifactResultResponse,
    BuildMessageSchema,
    BuildRequirementsSchema,
    BuildResultSchema,
    BuildStatusResponse,
    CancelBuildResponse,
    ChunkingDecisionSchema,
    DeploymentInfoSchema,
    EmbeddingBenchmarkResultSchema,
    EmbeddingDecisionSchema,
    FinalMetricsSchema,
    GenerationDecisionSchema,
    RetrievalDecisionSchema,
    StageStatusSchema,
    StartBuildRequest,
    StartBuildResponse,
    TargetMetricsSchema,
)

# ── Evaluation ────────────────────────────────────────────────────────────────
from app.schemas.evaluation import (
    CompareConfigsRequest,
    CompareConfigsResponse,
    EvaluationMetrics,
    EvaluationRunListResponse,
    EvaluationRunRequest,
    EvaluationRunResponse,
    FailureAnalysisResult,
    FailureCategory,
    MetricDelta,
    TestSetEntry,
)

# ── Deployment ────────────────────────────────────────────────────────────────
from app.schemas.deployment import (
    DeploymentListItem,
    DeploymentListResponse,
    DeploymentStatusResponse,
    DeployRequest,
    DeployResponse,
)

# ── Guardrails (P4.5) ─────────────────────────────────────────────────────────
from app.schemas.guardrails import (
    GuardrailsConfigSchema,
    GuardrailStageSettingsSchema,
    InputStageGuardrailsSchema,
    OutputStageGuardrailsSchema,
    RetrievalStageGuardrailsSchema,
)

__all__ = [
    # pipeline
    "RAGBaseModel",
    "CloudProvider",
    "ModelTier",
    "ChunkingStrategy",
    "VectorStoreProvider",
    "RetrievalStrategy",
    "EmbeddingProvider",
    "GenerationProvider",
    "MemoryType",
    "OutputFormat",
    "SimilarityMetric",
    "FilterOperator",
    "MetadataFilter",
    "HybridSearchConfig",
    "DataIngestionPreprocessingSchema",
    "DataIngestionMetadataSchema",
    "DataIngestionConfigSchema",
    "ChunkingConfigSchema",
    "EmbeddingConfigSchema",
    "VectorStoreCloudConfigSchema",
    "VectorStoreConfigurationSchema",
    "VectorStoreConfigSchema",
    "ParentChildConfigSchema",
    "MultiQueryConfigSchema",
    "RetrievalConfigSchema",
    "RerankingConfigSchema",
    "GenerationConfigSchema",
    "RoutingRuleSchema",
    "RoutingConfigSchema",
    "MemoryConfigSchema",
    "EvaluationConfigSchema",
    "PipelineStagesSchema",
    "PipelineMetadataSchema",
    "CostBreakdownSchema",
    "CostEstimateSchema",
    "PerformanceEstimateSchema",
    "PipelineConfigurationSchema",
    # projects (P4-1)
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectSummary",
    "ProjectDetailResponse",
    "PipelineConfigSummary",
    "AutopilotBuildSummary",
    "PaginatedProjectsResponse",
    # designer
    "SaveConfigRequest",
    "SaveConfigResponse",
    "UpdateDesignerConfigRequest",
    "ConfigListItem",
    "ConfigListResponse",
    "ExportFormat",
    "ExportRequest",
    "ExportResponse",
    "CostRequest",
    "CostResponse",
    # autopilot
    "TargetMetricsSchema",
    "BuildRequirementsSchema",
    "StartBuildRequest",
    "StartBuildResponse",
    "StageStatusSchema",
    "BuildMessageSchema",
    "EmbeddingBenchmarkResultSchema",
    "ChunkingDecisionSchema",
    "EmbeddingDecisionSchema",
    "RetrievalDecisionSchema",
    "GenerationDecisionSchema",
    "AgentDecisionSchema",
    "FinalMetricsSchema",
    "DeploymentInfoSchema",
    "BuildResultSchema",
    "BuildStatusResponse",
    "BuildArtifactResultResponse",
    "CancelBuildResponse",
    # evaluation
    "TestSetEntry",
    "EvaluationRunRequest",
    "EvaluationMetrics",
    "FailureCategory",
    "FailureAnalysisResult",
    "EvaluationRunResponse",
    "EvaluationRunListResponse",
    "CompareConfigsRequest",
    "MetricDelta",
    "CompareConfigsResponse",
    # deployment
    "DeployRequest",
    "DeployResponse",
    "DeploymentStatusResponse",
    "DeploymentListItem",
    "DeploymentListResponse",
    # guardrails (P4.5)
    "GuardrailStageSettingsSchema",
    "InputStageGuardrailsSchema",
    "OutputStageGuardrailsSchema",
    "RetrievalStageGuardrailsSchema",
    "GuardrailsConfigSchema",
]
