import type { PipelineConfiguration, PipelineStages } from '@/types/pipeline';

// ─── Provider-specific import maps ───────────────────────────────────────────

const EMBEDDING_IMPORTS: Record<string, string> = {
  openai: 'from langchain_openai import OpenAIEmbeddings',
  cohere: 'from langchain_cohere import CohereEmbeddings',
  google: 'from langchain_google_vertexai import VertexAIEmbeddings',
  huggingface: 'from langchain_huggingface import HuggingFaceEmbeddings',
  nomic: 'from langchain_community.embeddings import NomicEmbeddings',
  custom: '# Custom embedding — implement BaseEmbeddings',
};

const EMBEDDING_CLASS: Record<string, string> = {
  openai: 'OpenAIEmbeddings',
  cohere: 'CohereEmbeddings',
  google: 'VertexAIEmbeddings',
  huggingface: 'HuggingFaceEmbeddings',
  nomic: 'NomicEmbeddings',
  custom: 'CustomEmbeddings',
};

const LLM_IMPORTS: Record<string, string> = {
  openai: 'from langchain_openai import ChatOpenAI',
  anthropic: 'from langchain_anthropic import ChatAnthropic',
  google: 'from langchain_google_vertexai import ChatVertexAI',
  meta: 'from langchain_community.chat_models import ChatOllama',
  mistral: 'from langchain_mistralai import ChatMistralAI',
  cohere: 'from langchain_cohere import ChatCohere',
  custom: '# Custom LLM — implement BaseChatModel',
};

const LLM_CLASS: Record<string, string> = {
  openai: 'ChatOpenAI',
  anthropic: 'ChatAnthropic',
  google: 'ChatVertexAI',
  meta: 'ChatOllama',
  mistral: 'ChatMistralAI',
  cohere: 'ChatCohere',
  custom: 'CustomLLM',
};

const VECTORSTORE_IMPORTS: Record<string, string> = {
  qdrant: 'from langchain_qdrant import QdrantVectorStore\nfrom qdrant_client import QdrantClient',
  pinecone: 'from langchain_pinecone import PineconeVectorStore\nfrom pinecone import Pinecone',
  weaviate: 'from langchain_weaviate.vectorstores import WeaviateVectorStore\nimport weaviate',
  chroma: 'from langchain_chroma import Chroma',
  faiss: 'from langchain_community.vectorstores import FAISS',
  opensearch: 'from langchain_community.vectorstores import OpenSearchVectorSearch',
  'vertex-ai-vector-search': 'from langchain_google_vertexai.vectorstores import VectorSearchVectorStore',
  'azure-ai-search': 'from langchain_community.vectorstores import AzureSearch',
  pgvector: 'from langchain_postgres import PGVector',
};

const RETRIEVAL_SEARCH_TYPE: Record<string, string> = {
  similarity: 'similarity',
  mmr: 'mmr',
  hybrid: 'similarity',
  'parent-child': 'similarity',
  'multi-query': 'similarity',
  ensemble: 'similarity',
};

// ─── Code sections ────────────────────────────────────────────────────────────

function buildHeader(config: PipelineConfiguration): string {
  return `"""
RAG Pipeline — ${config.name}
Generated by RAG Studio
Cloud Provider: ${config.cloudProvider}
Model: ${config.stages.generation.model}
Vector Store: ${config.stages.vectorStore.provider}
Chunking: ${config.stages.chunking.strategy} (${config.stages.chunking.chunkSize} tokens)
"""`;
}

function buildImports(stages: PipelineStages): string {
  const lines: string[] = [
    'import os',
    ...(stages.humanInTheLoop?.enabled ? ['import json'] : []),
    'from typing import List',
    '',
    '# LangChain core',
    'from langchain_core.prompts import ChatPromptTemplate',
    'from langchain_core.output_parsers import StrOutputParser',
    'from langchain_core.runnables import RunnablePassthrough, RunnableParallel',
    'from langchain_core.documents import Document',
    '',
    '# Text splitting',
    'from langchain_text_splitters import RecursiveCharacterTextSplitter',
    '',
    `# Embeddings\n${EMBEDDING_IMPORTS[stages.embedding.provider] ?? EMBEDDING_IMPORTS.custom}`,
    '',
    `# LLM\n${LLM_IMPORTS[stages.generation.provider] ?? LLM_IMPORTS.custom}`,
    '',
    `# Vector store\n${VECTORSTORE_IMPORTS[stages.vectorStore.provider] ?? '# Vector store — add provider import'}`,
  ];

  if (stages.reranking?.enabled) {
    lines.push('');
    lines.push('# Reranking');
    if (stages.reranking.provider === 'cohere') {
      lines.push('from langchain_cohere import CohereRerank');
      lines.push('from langchain.retrievers.contextual_compression import ContextualCompressionRetriever');
    } else {
      lines.push('from langchain.retrievers.contextual_compression import ContextualCompressionRetriever');
      lines.push('from langchain.retrievers.document_compressors import CrossEncoderReranker');
      lines.push('from langchain_community.cross_encoders import HuggingFaceCrossEncoder');
    }
  }

  if (stages.memory && stages.memory.type !== 'none') {
    lines.push('');
    lines.push('# Memory');
    lines.push('from langchain.memory import ConversationBufferWindowMemory');
    lines.push('from langchain_core.chat_history import BaseChatMessageHistory');
    lines.push('from langchain_core.runnables.history import RunnableWithMessageHistory');
  }

  if (stages.retrieval.strategy === 'multi-query') {
    lines.push('');
    lines.push('# Multi-query retrieval');
    lines.push('from langchain.retrievers.multi_query import MultiQueryRetriever');
  }

  return lines.join('\n');
}

function buildHumanInTheLoopBlock(stages: PipelineStages): string[] {
  const h = stages.humanInTheLoop;
  if (!h?.enabled) return [];
  const cfg = {
    tier: h.tier,
    roles: h.roles,
    placement: h.placement,
    confidence: h.confidence,
    workflow: h.workflow,
    advanced: h.advanced,
  };
  const inner = JSON.stringify(cfg);
  return [
    '',
    '# ─── Human in the Loop (designer configuration) ─────────────────────────────',
    `HITL_CONFIG = json.loads(${JSON.stringify(inner)})`,
  ];
}

function buildConfig(stages: PipelineStages, cloudProvider: string): string {
  const embClass = EMBEDDING_CLASS[stages.embedding.provider] ?? 'CustomEmbeddings';
  const llmClass = LLM_CLASS[stages.generation.provider] ?? 'CustomLLM';

  const lines: string[] = [
    '# ─── Configuration ──────────────────────────────────────────────────────────',
    '',
    `CLOUD_PROVIDER = "${cloudProvider}"`,
    `INDEX_NAME = "${stages.vectorStore.indexName}"`,
    `EMBEDDING_MODEL = "${stages.embedding.model}"`,
    `EMBEDDING_DIMENSIONS = ${stages.embedding.dimensions}`,
    `LLM_MODEL = "${stages.generation.model}"`,
    `TEMPERATURE = ${stages.generation.temperature}`,
    `MAX_TOKENS = ${stages.generation.maxTokens}`,
    `CHUNK_SIZE = ${stages.chunking.chunkSize}`,
    `CHUNK_OVERLAP = ${stages.chunking.chunkOverlap}`,
    `TOP_K = ${stages.retrieval.topK}`,
    '',
    '# ─── Embeddings ─────────────────────────────────────────────────────────────',
    '',
    'embeddings = ' + buildEmbeddingInit(stages, embClass),
    '',
    '# ─── LLM ────────────────────────────────────────────────────────────────────',
    '',
    'llm = ' + buildLLMInit(stages, llmClass),
    '',
    '# ─── Text splitter ──────────────────────────────────────────────────────────',
    '',
    ...buildTextSplitter(stages),
    ...buildHumanInTheLoopBlock(stages),
  ];

  return lines.join('\n');
}

function buildEmbeddingInit(stages: PipelineStages, cls: string): string {
  switch (stages.embedding.provider) {
    case 'openai':
      return `${cls}(\n    model="${stages.embedding.model}"\n)`;
    case 'cohere':
      return `${cls}(\n    model="${stages.embedding.model}"\n)`;
    case 'google':
      return `${cls}(\n    model_name="${stages.embedding.model}"\n)`;
    case 'huggingface':
      return `${cls}(\n    model_name="${stages.embedding.model}"\n)`;
    default:
      return `${cls}(model="${stages.embedding.model}")`;
  }
}

function buildLLMInit(stages: PipelineStages, cls: string): string {
  const { generation: gen } = stages;
  const baseArgs = `model="${gen.model}",\n    temperature=${gen.temperature},\n    max_tokens=${gen.maxTokens}`;

  switch (gen.provider) {
    case 'openai':
      return `${cls}(\n    ${baseArgs}\n)`;
    case 'anthropic':
      return `${cls}(\n    model="${gen.model}",\n    temperature=${gen.temperature},\n    max_tokens=${gen.maxTokens}\n)`;
    case 'google':
      return `${cls}(\n    model_name="${gen.model}",\n    temperature=${gen.temperature},\n    max_output_tokens=${gen.maxTokens}\n)`;
    default:
      return `${cls}(\n    ${baseArgs}\n)`;
  }
}

function buildTextSplitter(stages: PipelineStages): string[] {
  const { strategy, chunkSize, chunkOverlap, separators } = stages.chunking;

  switch (strategy) {
    case 'recursive-character':
      return [
        'text_splitter = RecursiveCharacterTextSplitter(',
        `    chunk_size=${chunkSize},`,
        `    chunk_overlap=${chunkOverlap},`,
        separators ? `    separators=${JSON.stringify(separators)},` : '    separators=["\\n\\n", "\\n", " ", ""],',
        ')',
      ];
    case 'fixed-size':
      return [
        'from langchain_text_splitters import CharacterTextSplitter',
        '',
        'text_splitter = CharacterTextSplitter(',
        `    chunk_size=${chunkSize},`,
        `    chunk_overlap=${chunkOverlap},`,
        '    separator="",',
        ')',
      ];
    case 'markdown-header':
      return [
        'from langchain_text_splitters import MarkdownHeaderTextSplitter',
        '',
        'text_splitter = MarkdownHeaderTextSplitter(',
        '    headers_to_split_on=[',
        '        ("#", "Header 1"),',
        '        ("##", "Header 2"),',
        '        ("###", "Header 3"),',
        '    ]',
        ')',
      ];
    case 'sentence-based':
      return [
        '# Sentence-based splitter via NLTK',
        'from langchain_text_splitters import NLTKTextSplitter',
        '',
        `text_splitter = NLTKTextSplitter(chunk_size=${chunkSize})`,
      ];
    case 'semantic':
      return [
        '# Semantic chunking requires sentence-transformers',
        'from langchain_experimental.text_splitter import SemanticChunker',
        '',
        'text_splitter = SemanticChunker(',
        '    embeddings,',
        '    breakpoint_threshold_type="percentile",',
        ')',
      ];
    default:
      return [
        'text_splitter = RecursiveCharacterTextSplitter(',
        `    chunk_size=${chunkSize},`,
        `    chunk_overlap=${chunkOverlap},`,
        ')',
      ];
  }
}

function buildVectorStore(stages: PipelineStages): string {
  const { vectorStore } = stages;
  const metric = vectorStore.configuration.metric ?? 'cosine';

  switch (vectorStore.provider) {
    case 'qdrant':
      return [
        '# ─── Vector Store (Qdrant) ──────────────────────────────────────────────────',
        '',
        'qdrant_client = QdrantClient(',
        '    url=os.environ["QDRANT_URL"],',
        '    api_key=os.environ.get("QDRANT_API_KEY"),',
        ')',
        '',
        `vector_store = QdrantVectorStore(`,
        '    client=qdrant_client,',
        `    collection_name="${vectorStore.indexName}",`,
        '    embedding=embeddings,',
        `    distance="${metric.toUpperCase()}",`,
        ')',
      ].join('\n');

    case 'pinecone':
      return [
        '# ─── Vector Store (Pinecone) ────────────────────────────────────────────────',
        '',
        'pc = Pinecone(api_key=os.environ["PINECONE_API_KEY"])',
        `index = pc.Index("${vectorStore.indexName}")`,
        '',
        'vector_store = PineconeVectorStore(',
        '    index=index,',
        '    embedding=embeddings,',
        ')',
      ].join('\n');

    case 'chroma':
      return [
        '# ─── Vector Store (Chroma) ──────────────────────────────────────────────────',
        '',
        'vector_store = Chroma(',
        `    collection_name="${vectorStore.indexName}",`,
        '    embedding_function=embeddings,',
        '    persist_directory="./chroma_db",',
        ')',
      ].join('\n');

    case 'pgvector':
      return [
        '# ─── Vector Store (pgvector) ────────────────────────────────────────────────',
        '',
        'vector_store = PGVector(',
        `    collection_name="${vectorStore.indexName}",`,
        '    connection=os.environ["DATABASE_URL"],',
        '    embeddings=embeddings,',
        ')',
      ].join('\n');

    default:
      return [
        `# ─── Vector Store (${vectorStore.provider}) ─────────────────────────────────`,
        '',
        '# TODO: configure your vector store connection',
        'vector_store = None  # replace with actual initialisation',
      ].join('\n');
  }
}

function buildRetriever(stages: PipelineStages): string {
  const { retrieval, reranking } = stages;
  const searchType = RETRIEVAL_SEARCH_TYPE[retrieval.strategy] ?? 'similarity';
  const lines: string[] = [
    '# ─── Retriever ──────────────────────────────────────────────────────────────',
    '',
  ];

  switch (retrieval.strategy) {
    case 'mmr':
      lines.push(
        'base_retriever = vector_store.as_retriever(',
        '    search_type="mmr",',
        `    search_kwargs={"k": ${retrieval.topK}, "fetch_k": ${retrieval.topK * 4}},`,
        ')'
      );
      break;
    case 'hybrid':
      lines.push(
        '# Hybrid dense+sparse retrieval',
        'base_retriever = vector_store.as_retriever(',
        '    search_type="similarity",',
        `    search_kwargs={"k": ${retrieval.topK}},`,
        ')',
        '# TODO: combine with BM25Retriever using EnsembleRetriever:',
        '# from langchain.retrievers import EnsembleRetriever, BM25Retriever',
        '# bm25 = BM25Retriever.from_documents(docs, k=TOP_K)',
        `# retriever = EnsembleRetriever(retrievers=[bm25, base_retriever], weights=[${1 - (retrieval.hybridSearch?.alpha ?? 0.5)}, ${retrieval.hybridSearch?.alpha ?? 0.5}])`
      );
      break;
    case 'multi-query':
      lines.push(
        'base_retriever = MultiQueryRetriever.from_llm(',
        '    retriever=vector_store.as_retriever(',
        `        search_kwargs={"k": ${retrieval.topK}}`,
        '    ),',
        '    llm=llm,',
        ')'
      );
      break;
    default:
      lines.push(
        'base_retriever = vector_store.as_retriever(',
        `    search_type="${searchType}",`,
        `    search_kwargs={"k": ${retrieval.topK}},`,
        ')'
      );
  }

  if (reranking?.enabled) {
    lines.push('');
    lines.push('# Reranking with contextual compression');
    if (reranking.provider === 'cohere') {
      lines.push(`compressor = CohereRerank(top_n=${reranking.topN ?? 5})`);
    } else {
      lines.push(`model = HuggingFaceCrossEncoder(model_name="${reranking.model ?? 'cross-encoder/ms-marco-MiniLM-L-6-v2'}")`);
      lines.push(`compressor = CrossEncoderReranker(model=model, top_n=${reranking.topN ?? 5})`);
    }
    lines.push('retriever = ContextualCompressionRetriever(');
    lines.push('    base_compressor=compressor,');
    lines.push('    base_retriever=base_retriever,');
    lines.push(')');
  } else {
    lines.push('retriever = base_retriever');
  }

  return lines.join('\n');
}

function buildPromptAndChain(stages: PipelineStages): string {
  const systemPrompt =
    stages.generation.systemPrompt ??
    'You are a helpful assistant. Use the provided context to answer the question accurately.';

  const formatInstruction =
    stages.generation.outputFormat === 'json'
      ? 'Return your answer as valid JSON.'
      : stages.generation.outputFormat === 'markdown'
      ? 'Format your answer using Markdown.'
      : '';

  const lines: string[] = [
    '# ─── Prompt ─────────────────────────────────────────────────────────────────',
    '',
    'prompt = ChatPromptTemplate.from_messages([',
    '    ("system", """' + systemPrompt,
    '',
    'Context:',
    '{context}',
    (formatInstruction ? formatInstruction + '\n"""),' : '"""),'),
    '    ("human", "{question}"),',
    '])',
    '',
    '# ─── Chain (LCEL) ───────────────────────────────────────────────────────────',
    '',
    'def format_docs(docs: List[Document]) -> str:',
    '    return "\\n\\n".join(doc.page_content for doc in docs)',
    '',
    'rag_chain = (',
    '    RunnableParallel(',
    '        context=retriever | format_docs,',
    '        question=RunnablePassthrough(),',
    '    )',
    '    | prompt',
    '    | llm',
    '    | StrOutputParser()',
    ')',
  ];

  if (stages.memory && stages.memory.type !== 'none') {
    const windowSize = stages.memory.windowSize ?? 10;
    lines.push('');
    lines.push('# ─── Memory ─────────────────────────────────────────────────────────────────');
    lines.push('');
    lines.push('store: dict[str, BaseChatMessageHistory] = {}');
    lines.push('');
    lines.push('def get_session_history(session_id: str) -> BaseChatMessageHistory:');
    lines.push('    from langchain_core.chat_history import InMemoryChatMessageHistory');
    lines.push('    if session_id not in store:');
    lines.push('        store[session_id] = InMemoryChatMessageHistory()');
    lines.push('    return store[session_id]');
    lines.push('');
    lines.push(`memory = ConversationBufferWindowMemory(k=${windowSize}, return_messages=True)`);
    lines.push('');
    lines.push('rag_chain_with_history = RunnableWithMessageHistory(');
    lines.push('    rag_chain,');
    lines.push('    get_session_history,');
    lines.push('    input_messages_key="question",');
    lines.push('    history_messages_key="chat_history",');
    lines.push(')');
  }

  return lines.join('\n');
}

function buildIndexingSection(stages: PipelineStages): string {
  return [
    '# ─── Indexing helper ────────────────────────────────────────────────────────',
    '',
    'def index_documents(file_paths: list[str]) -> int:',
    '    """Load, chunk, embed, and store documents. Returns chunk count."""',
    '    from langchain_community.document_loaders import UnstructuredFileLoader',
    '    ',
    '    all_docs: List[Document] = []',
    '    for path in file_paths:',
    '        loader = UnstructuredFileLoader(path)',
    '        all_docs.extend(loader.load())',
    '    ',
    '    chunks = text_splitter.split_documents(all_docs)',
    '    vector_store.add_documents(chunks)',
    '    return len(chunks)',
    '',
    '',
    '# ─── Inference ──────────────────────────────────────────────────────────────',
    '',
    'def query(question: str, session_id: str = "default") -> str:',
    '    """Run a RAG query and return the generated answer."""',
    stages.memory && stages.memory.type !== 'none'
      ? '    return rag_chain_with_history.invoke(\n        {"question": question},\n        config={"configurable": {"session_id": session_id}},\n    )'
      : '    return rag_chain.invoke(question)',
    '',
    '',
    'if __name__ == "__main__":',
    '    # Quick smoke test',
    '    answer = query("What is this document about?")',
    '    print(answer)',
  ].join('\n');
}

/**
 * Generates a complete, runnable LangChain LCEL Python script for the given
 * `PipelineConfiguration`. The output can be saved as a `.py` file and run
 * directly after installing the listed dependencies.
 */
export function generatePythonCode(config: PipelineConfiguration): string {
  const { stages, cloudProvider } = config;

  const sections = [
    buildHeader(config),
    '',
    buildImports(stages),
    '',
    '',
    buildConfig(stages, cloudProvider),
    '',
    '',
    buildVectorStore(stages),
    '',
    '',
    buildRetriever(stages),
    '',
    '',
    buildPromptAndChain(stages),
    '',
    '',
    buildIndexingSection(stages),
  ];

  return sections.join('\n');
}
