import type { PipelineConfiguration, PipelineStages } from '@/types/pipeline';

type CloudProvider = 'aws' | 'gcp' | 'azure' | 'multi-cloud';
type SupportedCloud = 'aws' | 'gcp' | 'azure';

// ─── Header helpers ───────────────────────────────────────────────────────────

function tfHeader(config: PipelineConfiguration, cloud: string): string {
  return `# RAG Studio — Terraform Configuration
# Pipeline: ${config.name}
# Cloud: ${cloud}
# Generated by RAG Studio
#
# Usage:
#   terraform init
#   terraform plan -var-file="terraform.tfvars"
#   terraform apply
`;
}

function tfVariables(cloud: string): string {
  const base = `variable "project_name" {
  description = "Name used to prefix all RAG Studio resources"
  type        = string
  default     = "rag-studio"
}

variable "environment" {
  description = "Deployment environment (dev / staging / prod)"
  type        = string
  default     = "dev"
}

variable "region" {
  description = "Primary deployment region"
  type        = string
}`;

  if (cloud === 'aws') {
    return base + `

variable "aws_account_id" {
  description = "AWS account ID for IAM policies"
  type        = string
}

variable "openai_api_key" {
  description = "OpenAI API key (stored in Secrets Manager)"
  type        = string
  sensitive   = true
  default     = ""
}`;
  }

  if (cloud === 'gcp') {
    return base + `

variable "gcp_project_id" {
  description = "Google Cloud project ID"
  type        = string
}`;
  }

  if (cloud === 'azure') {
    return base + `

variable "subscription_id" {
  description = "Azure subscription ID"
  type        = string
}

variable "resource_group_name" {
  description = "Azure resource group for all RAG Studio resources"
  type        = string
  default     = "rg-rag-studio"
}`;
  }

  return base;
}

// ─── Provider blocks ──────────────────────────────────────────────────────────

function awsProvider(): string {
  return `terraform {
  required_version = ">= 1.6"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    # Configure remote state in terraform.tfvars
    # bucket = "your-terraform-state-bucket"
    # key    = "rag-studio/terraform.tfstate"
    # region = "us-east-1"
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}`;
}

function gcpProvider(): string {
  return `terraform {
  required_version = ">= 1.6"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }

  backend "gcs" {
    # bucket = "your-tf-state-bucket"
    # prefix = "rag-studio"
  }
}

provider "google" {
  project = var.gcp_project_id
  region  = var.region
}`;
}

function azureProvider(): string {
  return `terraform {
  required_version = ">= 1.6"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }

  backend "azurerm" {
    # resource_group_name  = "rg-terraform-state"
    # storage_account_name = "tfstateaccount"
    # container_name       = "tfstate"
    # key                  = "rag-studio.terraform.tfstate"
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}`;
}

// ─── Compute resources ────────────────────────────────────────────────────────

function awsCompute(): string {
  return `# ─── ECS Cluster ─────────────────────────────────────────────────────────────

resource "aws_ecs_cluster" "main" {
  name = "\${var.project_name}-\${var.environment}"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

# ─── RAG API — ECS Service ───────────────────────────────────────────────────

resource "aws_ecs_task_definition" "api" {
  family                   = "\${var.project_name}-api"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "1024"
  memory                   = "2048"
  execution_role_arn       = aws_iam_role.ecs_execution.arn
  task_role_arn            = aws_iam_role.ecs_task.arn

  container_definitions = jsonencode([{
    name  = "api"
    image = "\${var.aws_account_id}.dkr.ecr.\${var.region}.amazonaws.com/\${var.project_name}-api:latest"
    portMappings = [{ containerPort = 8000, protocol = "tcp" }]
    environment = [
      { name = "QDRANT_URL", value = "http://\${aws_lb.qdrant.dns_name}:6333" },
    ]
    secrets = [
      { name = "OPENAI_API_KEY", valueFrom = aws_secretsmanager_secret.openai.arn },
    ]
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = "/ecs/\${var.project_name}"
        "awslogs-region"        = var.region
        "awslogs-stream-prefix" = "api"
      }
    }
  }])
}

resource "aws_ecs_service" "api" {
  name            = "\${var.project_name}-api"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.api.arn
  desired_count   = 2
  launch_type     = "FARGATE"

  network_configuration {
    subnets         = aws_subnet.private[*].id
    security_groups = [aws_security_group.api.id]
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.api.arn
    container_name   = "api"
    container_port   = 8000
  }
}`;
}

function gcpCompute(): string {
  return `# ─── Cloud Run — RAG API ─────────────────────────────────────────────────────

resource "google_cloud_run_v2_service" "api" {
  name     = "\${var.project_name}-api"
  location = var.region

  template {
    containers {
      image = "gcr.io/\${var.gcp_project_id}/\${var.project_name}-api:latest"
      ports { container_port = 8000 }

      resources {
        limits = {
          cpu    = "2"
          memory = "2Gi"
        }
      }

      env {
        name  = "QDRANT_URL"
        value = "http://qdrant:6333"
      }

      env {
        name = "OPENAI_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.openai.secret_id
            version = "latest"
          }
        }
      }
    }

    scaling {
      min_instance_count = 1
      max_instance_count = 10
    }
  }
}

resource "google_cloud_run_v2_service_iam_member" "public" {
  name     = google_cloud_run_v2_service.api.name
  location = google_cloud_run_v2_service.api.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}`;
}

function azureCompute(): string {
  return `# ─── Resource Group ──────────────────────────────────────────────────────────

resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.region
}

# ─── Container Apps Environment ───────────────────────────────────────────────

resource "azurerm_container_app_environment" "main" {
  name                = "\${var.project_name}-env"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_container_app" "api" {
  name                         = "\${var.project_name}-api"
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = azurerm_resource_group.main.name
  revision_mode                = "Single"

  template {
    container {
      name   = "api"
      image  = "acrragstudio.azurecr.io/\${var.project_name}-api:latest"
      cpu    = 1
      memory = "2Gi"

      env {
        name  = "QDRANT_URL"
        value = "http://qdrant:6333"
      }
    }

    min_replicas = 1
    max_replicas = 10
  }

  ingress {
    external_enabled = true
    target_port      = 8000
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }
}`;
}

// ─── Vector store resources ───────────────────────────────────────────────────

function vectorStoreResources(stages: PipelineStages, cloud: string): string {
  const provider = stages.vectorStore.provider;
  const indexName = stages.vectorStore.indexName;

  if (provider === 'qdrant') {
    if (cloud === 'aws') {
      return `# ─── Qdrant (self-hosted on ECS) ─────────────────────────────────────────────

resource "aws_ecs_task_definition" "qdrant" {
  family                   = "\${var.project_name}-qdrant"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "512"
  memory                   = "1024"

  container_definitions = jsonencode([{
    name  = "qdrant"
    image = "qdrant/qdrant:latest"
    portMappings = [{ containerPort = 6333 }]
    mountPoints  = [{ sourceVolume = "qdrant-storage", containerPath = "/qdrant/storage" }]
  }])

  volume {
    name = "qdrant-storage"
    efs_volume_configuration {
      file_system_id = aws_efs_file_system.qdrant.id
    }
  }
}`;
    }
    if (cloud === 'gcp') {
      return `# ─── Qdrant (Cloud Run) ─────────────────────────────────────────────────────

resource "google_cloud_run_v2_service" "qdrant" {
  name     = "\${var.project_name}-qdrant"
  location = var.region

  template {
    containers {
      image = "qdrant/qdrant:latest"
      ports { container_port = 6333 }
      resources { limits = { cpu = "1", memory = "1Gi" } }
      volume_mounts { name = "qdrant-storage", mount_path = "/qdrant/storage" }
    }
    volumes {
      name = "qdrant-storage"
      gcs { bucket = google_storage_bucket.qdrant.name }
    }
  }
}`;
    }
    return `# ─── Qdrant (Azure Container App) ───────────────────────────────────────────

resource "azurerm_container_app" "qdrant" {
  name                         = "\${var.project_name}-qdrant"
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = azurerm_resource_group.main.name
  revision_mode                = "Single"

  template {
    container {
      name   = "qdrant"
      image  = "qdrant/qdrant:latest"
      cpu    = 0.5
      memory = "1Gi"
    }
  }

  ingress {
    external_enabled = false
    target_port      = 6333
    traffic_weight { latest_revision = true, percentage = 100 }
  }
}`;
  }

  if (provider === 'pinecone') {
    return `# ─── Pinecone Index ──────────────────────────────────────────────────────────
# Pinecone is a managed service; provisioning is done via the Pinecone API.
# The index is referenced by name in the application.

# Optionally store API key in cloud secrets manager:
${cloud === 'aws' ? `resource "aws_secretsmanager_secret" "pinecone" {
  name = "\${var.project_name}/pinecone-api-key"
}` : cloud === 'gcp' ? `resource "google_secret_manager_secret" "pinecone" {
  secret_id = "\${var.project_name}-pinecone-api-key"
  replication { auto {} }
}` : `resource "azurerm_key_vault_secret" "pinecone" {
  name         = "pinecone-api-key"
  value        = "REPLACE_ME"
  key_vault_id = azurerm_key_vault.main.id
}`}

# Index name used by the application: "${indexName}"`;
  }

  return `# ─── Vector Store (${provider}) ──────────────────────────────────────────────
# TODO: add Terraform resources for ${provider} on ${cloud}
# Index name: ${indexName}`;
}

// ─── Secrets ─────────────────────────────────────────────────────────────────

function secretResources(stages: PipelineStages, cloud: string): string {
  if (cloud === 'aws') {
    return `# ─── Secrets Manager ─────────────────────────────────────────────────────────

resource "aws_secretsmanager_secret" "openai" {
  name = "\${var.project_name}/openai-api-key"
}

resource "aws_secretsmanager_secret_version" "openai" {
  secret_id     = aws_secretsmanager_secret.openai.id
  secret_string = var.openai_api_key
}`;
  }

  if (cloud === 'gcp') {
    return `# ─── Secret Manager ──────────────────────────────────────────────────────────

resource "google_secret_manager_secret" "openai" {
  secret_id = "\${var.project_name}-openai-api-key"
  replication { auto {} }
}`;
  }

  if (cloud === 'azure') {
    return `# ─── Key Vault ───────────────────────────────────────────────────────────────

data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "main" {
  name                = "\${var.project_name}-kv"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}`;
  }

  return '# Secrets: configure for your cloud provider';
}

// ─── Outputs ──────────────────────────────────────────────────────────────────

function outputs(cloud: string): string {
  if (cloud === 'aws') {
    return `# ─── Outputs ─────────────────────────────────────────────────────────────────

output "api_endpoint" {
  description = "Load balancer DNS name for the RAG API"
  value       = "https://\${aws_lb.main.dns_name}"
}`;
  }

  if (cloud === 'gcp') {
    return `# ─── Outputs ─────────────────────────────────────────────────────────────────

output "api_endpoint" {
  description = "Cloud Run URL for the RAG API"
  value       = google_cloud_run_v2_service.api.uri
}`;
  }

  if (cloud === 'azure') {
    return `# ─── Outputs ─────────────────────────────────────────────────────────────────

output "api_endpoint" {
  description = "Container App FQDN for the RAG API"
  value       = "https://\${azurerm_container_app.api.ingress[0].fqdn}"
}`;
  }

  return `output "api_endpoint" {
  value = "Configure your endpoint for multi-cloud"
}`;
}

/**
 * Generates a Terraform HCL configuration for the given `PipelineConfiguration`.
 * Provider-specific resources are scaffolded for AWS, GCP, and Azure.
 * Multi-cloud falls back to AWS with a comment.
 */
export function generateTerraform(config: PipelineConfiguration): string {
  const raw = config.cloudProvider as string;
  const cloud: SupportedCloud = raw === 'multi-cloud' ? 'aws' : (raw as SupportedCloud);
  const { stages } = config;

  const providerFns: Record<SupportedCloud, () => string> = {
    aws: awsProvider,
    gcp: gcpProvider,
    azure: azureProvider,
  };

  const computeFns: Record<SupportedCloud, () => string> = {
    aws: awsCompute,
    gcp: gcpCompute,
    azure: azureCompute,
  };

  const providerBlock = providerFns[cloud]?.() ?? awsProvider();
  const computeBlock = computeFns[cloud]?.() ?? awsCompute();

  const sections: string[] = [
    tfHeader(config, raw),
    tfVariables(cloud),
    '',
    providerBlock,
    '',
    computeBlock,
    '',
    vectorStoreResources(stages, cloud),
    '',
    secretResources(stages, cloud),
    '',
    outputs(cloud),
  ];

  return sections.join('\n');
}
